spring.application.name=Nexsta
instanceId=1
server.port=8080
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER}
keycloak.clientId=${KEYCLOAK_CLIENT}
keycloak.clientSecret=${KEYCLOAK_SECRET}
server.forward-headers-strategy=framework
server.use-forward-headers=true
supabase.url=${SUPABASE_URL}
supabase.apiKey=${SUPABASE_APIKEY}
supabase.endpoint=/storage/v1/object
supabase.PublicMediaBucket=${SUPABASE_PUBLIC_BUCKET}
supabase.PrivateMediaBucket=${SUPABASE_PRIVATE_BUCKET}
supabase.BatchFileMoveEndpoint=/functions/v1/${FILE_MOVE}
supabase.BatchTempFileMoveEndpoint=/functions/v1/${TEMPORARY_FILE_MOVE}
supabase.webhook.secret=${SUPABASE_WEBHOOK_SECRET}

brevo.url=https://api.brevo.com/v3
brevo.apiKey=${BREVO_APIKEY}
brevo.emailSender=${BREVO_EMAIL_SENDER}

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.data.mongodb.uri=mongodb://localhost:27017/SocialMediaDB
spring.data.mongodb.database=yourdb

spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
spring.quartz.properties.org.quartz.scheduler.instanceName=MyScheduler
spring.quartz.properties.org.quartz.jobStore.class=org.springframework.scheduling.quartz.LocalDataSourceJobStore
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.threadPool.threadCount=5